replicaCount: 1

fullnameOverride: "k8sman-agent"

image:
  repository: k8sman/k8sman-agent
  pullPolicy: Always
  tag: "latest"

serviceAccount:
  create: true
  name: "k8sman-agent"

k8sman:
  enable_tls: "false"
  server: "localhost:5556"

# this force an secret-key to identify the agent
clusterIdentifier: "f2teDZCZlOEusFirGw5U"

resources: {}
