apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8sman-agent.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "k8sman-agent.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "k8sman-agent.name" . }}
    spec:
      serviceAccountName: {{ include "k8sman-agent.name" . | quote}}
      containers:
        - name: k8sman-agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: K8SMAN_AGENT_NAME
              value: {{ include "k8sman-agent.name" . }}
