apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8sman-agent.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "k8sman-agent.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "k8sman-agent.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      containers:
        - name: k8sman-agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: RABBITMQ_HOST
              value: {{ .Values.rabbitmq.host | quote }}
            - name: RABBITMQ_VHOST
              value: {{ .Values.rabbitmq.vhost | quote }}
            - name: RABBITMQ_USER
              value: {{ .Values.rabbitmq.user | quote }}
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "k8sman-agent.name" . }}-secret
                  key: rabbitmq-pass
            - name: RABBITMQ_USE_TLS
              value: "{{ .Values.rabbitmq.useTLS | toString }}"
            - name: RABBITMQ_PORT
              value: "{{ .Values.rabbitmq.port | toString }}"
          {{- if .Values.rabbitmq.useTLS }}
          volumeMounts:
            - name: rabbitmq-cert
              mountPath: "/etc/rabbitmq_cert" # no change this
              readOnly: true
            - name: rabbitmq-key
              mountPath: "/etc/rabbitmq_key" # no change this
              readOnly: true
          {{- end }}
      {{- if .Values.rabbitmq.useTLS }}
      volumes:
        - name: rabbitmq-cert
          secret:
            secretName: {{ include "k8sman-agent.name" . }}-secret
            items:
              - key: rabbitmq-cert
                path: certificate.crt # no change this
        - name: rabbitmq-key
          secret:
            secretName: {{ include "k8sman-agent.name" . }}-secret
            items:
              - key: rabbitmq-key
                path: certificate.key # no change this
      {{- end }}
 