apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "k8sman-agent.name" . }}-job-tls
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: job-tls
        image: alpine/openssl  
        command: ["/bin/sh", "-c"]
        args: 
        - |
          openssl req -x509 -newkey rsa:4096 -keyout /tmp/tls.key -out /tmp/tls.crt -days 365 -nodes -subj "/CN={{ .Values.rabbitmq.host }}"
          kubectl create secret generic {{ include "k8sman-agent.name" . }}-tls --from-file=/tmp/tls.crt --from-file=/tmp/tls.key -n {{ .Release.Namespace }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      restartPolicy: OnFailure
      volumes:
      - name: tmp
        emptyDir: {}
