apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8sman-agent-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "namespaces", "deployments", "nodes", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8sman-agent-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: "k8sman-agent"
  namespace: default
roleRef:
  kind: ClusterRole
  name: k8sman-agent-clusterrole
  apiGroup: rbac.authorization.k8s.io
  