apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8sman-agent.name" . }}-secret
type: Opaque
data:
  rabbitmq-pass: {{ .Values.rabbitmq.pass | b64enc | quote }}
  {{- if .Values.rabbitmq.useTLS }}
  rabbitmq-cert: {{ .Files.Get .Values.rabbitmq.certPath | b64enc | quote }}
  rabbitmq-key: {{ .Files.Get .Values.rabbitmq.keyPath | b64enc | quote }}
  {{- end }}
