apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8sman-agent.name" . }}-secret
type: Opaque
data:
  rabbitmq-pass: {{ .Values.rabbitmq.pass | b64enc | quote }}
  cluster-identifier: {{ randAlphaNum 20 | b64enc | quote }}
