apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8sman-agent.name" . }}-secret
type: Opaque
data:
  rabbitmq-pass: {{ .Values.rabbitmq.pass | b64enc | quote }}
  cluster-identifier: {{ (default (randAlphaNum 20) .Values.clusterIdentifier) | b64enc | quote }}
