apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8sman-agent.fullname" . }}
  labels:
    app: {{ include "k8sman-agent.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
