name: Bump Helm Chart Version

on:
  push:
    branch:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Create New Branch
      run: |
        new_branch="bump-version-$(date +%s)"
        git checkout -b $new_branch

    - name: Install yq
      run: |
        sudo snap install yq

    - name: Bump Minor Version
      run: |
        version=$(yq e '.version' ./charts/k8sman-agent/Chart.yaml)
        IFS='.' read -ra VER <<< "$version"
        ((VER[1]++))
        VER[2]=0 # Reset patch version
        new_version="${VER[0]}.${VER[1]}.${VER[2]}"
        yq e ".version = \"$new_version\"" -i ./charts/k8sman-agent/Chart.yaml
        git add ./charts/k8sman-agent/Chart.yaml
        git commit -m "Bump chart version to $new_version"
        new_branch="bump-version-$(date +%s)"
        git checkout -b $new_branch
        git push --set-upstream origin $new_branch

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_branch: ${{ env.new_branch }}
        destination_branch: "main"
        pr_title: "Bump chart version to $new_version"
        pr_body: "Automated version bump to $new_version"
        pr_label: "version-bump"
