name: Bump Helm Chart Version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Create Unique Version Branch
      run: |
        UNIQUE_BRANCH="version-bump-${GITHUB_RUN_NUMBER}"
        git checkout -b $UNIQUE_BRANCH
        echo "UNIQUE_BRANCH=$UNIQUE_BRANCH" >> $GITHUB_ENV

    - name: Increment Chart Version
      run: |
        VERSION=$(grep 'version:' charts/k8sman-agent/Chart.yaml | awk '{print $2}')
        IFS='.' read -ra VER <<< "$VERSION"
        ((VER[1]++))
        NEW_VERSION="${VER[0]}.${VER[1]}.${VER[2]}"
        sed -i "s/version: $VERSION/version: $NEW_VERSION/" charts/k8sman-agent/Chart.yaml
        git add charts/k8sman-agent/Chart.yaml
        git commit -m "Increment chart version to $NEW_VERSION"
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Push to Unique Version Branch
      run: |
        git push --set-upstream origin ${{ env.UNIQUE_BRANCH }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ${{ env.UNIQUE_BRANCH }}
        destination_branch: "main"
        pr_title: "Update chart version to ${{ env.NEW_VERSION }}"
        pr_body: "Automatic version bump to ${{ env.NEW_VERSION }}"
        github_token: ${{ secrets.GITHUB_TOKEN }}
