name: Bump Helm Chart Version

on:
  push:
    branch:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Create Unique Version Branch
      run: |
        UNIQUE_BRANCH="version-bump-${GITHUB_RUN_NUMBER}"
        git checkout -b $UNIQUE_BRANCH

    - name: Increment Chart Version
      run: |
        VERSION=$(grep 'version:' charts/k8sman-agent/Chart.yaml | awk '{print $2}')
        NEW_VERSION=$(echo $VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
        sed -i "s/version: $VERSION/version: $NEW_VERSION/" charts/k8sman-agent/Chart.yaml
        git add charts/k8sman-agent/Chart.yaml
        git commit -m "Increment chart version to $NEW_VERSION"

    - name: Push to Unique Version Branch and Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ${{ env.UNIQUE_BRANCH }}
        destination_branch: "main"
        pr_title: "Update chart version to $NEW_VERSION"
        github_token: ${{ secrets.GITHUB_TOKEN }}

