name: Merge and Version Bump

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - name: Bump Minor Version in Chart.yaml
        run: |
          python3 -c "import yaml
          with open('charts/k8sman-agent/Chart.yaml', 'r') as file:
              chart = yaml.safe_load(file)
              version = chart['version'].split('.')
              version[1] = str(int(version[1]) + 1)
              chart['version'] = '.'.join(version)
          with open('charts/k8sman-agent/Chart.yaml', 'w') as file:
              yaml.dump(chart, file, default_flow_style=False)"
        shell: bash

      - name: Commit and Push Version Bump
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git checkout -b version-bump
          git add charts/k8sman-agent/Chart.yaml
          git commit -m "Increment minor version"
          git push origin version-bump

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh

      - name: Create Pull Request
        run: |
          gh pr create --base main --head version-bump --title 'Merge version-bump into main' --body 'This PR increments the minor version of the Helm Chart. Created by Github action.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
