name: Publish Helm Chart
#on:
#  push:
#    paths:
#      - 'charts/**'
#      - 'Chart.yaml'
on:
  push:
    branches:
      - main
      
permissions:
  contents: write

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm 
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - name: Configure Git (package metadata) 
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Increment Chart Version
        run: |
          # Read the current version
          VERSION=$(grep 'version:' charts/k8sman-agent/Chart.yaml | awk '{print $2}')
          # Increment the version
          NEW_VERSION=$(echo $VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          # Update the file with the new version
          sed -i "s/version: $VERSION/version: $NEW_VERSION/" charts/k8sman-agent/Chart.yaml
          # Commit and push the changes
          git add charts/k8sman-agent/Chart.yaml
          git commit -m "Increment chart version to $NEW_VERSION"
          git push

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
