name: Publish Helm Chart
on:
  push:
    paths:
      - 'charts/**'
      - 'Chart.yaml'
  permissions:
    contents: write

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Package Helm Chart
      run: |
        helm package ./charts/k8sman-agent -d ./charts

    - name: Reindex Helm Repo
      run: |
        helm repo index ./charts --url https://ovrdoz.github.io/k8sman-helm-chart/charts/
  
    - name: Commit Charts Directory
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add ./charts/
        if git diff --staged --quiet; then
          echo "Nenhuma alteração no diretório ./charts/, pulando o commit."
        else
          git commit -m "Publish updated Helm chart [skip ci]"
          git push
        fi

